"""empty message

Revision ID: 0e3d842a4c76
Revises: 67d3d4d10ade
Create Date: 2017-04-26 18:28:43.875870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3d842a4c76'
down_revision = '67d3d4d10ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('height', sa.String(), nullable=True))
    op.add_column('post', sa.Column('width', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'width')
    op.drop_column('post', 'height')
    # ### end Alembic commands ###
