"""empty message

Revision ID: 67d3d4d10ade
Revises: f5ef4960a7b6
Create Date: 2017-04-25 19:50:50.102569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d3d4d10ade'
down_revision = 'f5ef4960a7b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('directory', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['directory'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'directory')
    # ### end Alembic commands ###
