"""empty message

Revision ID: f5ef4960a7b6
Revises: d577d1aa5084
Create Date: 2017-03-04 15:46:35.571176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ef4960a7b6'
down_revision = 'd577d1aa5084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
